;this file for FamiTone2 library generated by text2data tool

DMCmusic_dialogue6_data:
	.byte 1
	.word 1
	.word .Lsamples-3

.Lsamples:
	.byte $00+__dpcm_offset,$ff,$0d	;1 (yourfirstchallen)
	.byte $40+__dpcm_offset,$cf,$0c	;2 (youllbeontheothe)
