;this file for FamiTone2 library generated by text2data tool

DMCmusic_dialogue5_data:
	.byte 1
	.word 1
	.word .Lsamples-3

.Lsamples:
	.byte $00+__dpcm_offset,$ff,$0e	;1 (dontbescareditwi)
	.byte $40+__dpcm_offset,$ff,$0d	;2 (proveyourworthin)
