;this file for FamiTone2 library generated by text2data tool

DMCmusic_dialogue3_data:
	.byte 1
	.word 1
	.word .Lsamplesd3-3

.Lsamplesd3:
	.byte $00+__dpcm_offset,$ff,$0e	;1 
	.byte $40+__dpcm_offset,$ff,$0e	;2
