;this file for FamiTone2 library generated by text2data tool

DMCmusic_music_data:
	.byte 1
	.word .Linstruments
	.word .Lsamples-3

.Linstruments:
	.byte $b0 ;instrument $00
	.word .Lenv1,.Lenv0,.Lenv0
	.byte $00
	.byte $b0 ;instrument $01
	.word .Lenv1,.Lenv0,.Lenv0
	.byte $00
	.byte $b0 ;instrument $02
	.word .Lenv2,.Lenv0,.Lenv0
	.byte $00

.Lsamples:
	.byte $00+__dpcm_offset,$19,$02	;52 (fuck2)
	.byte $07+__dpcm_offset,$11,$02	;53 (fuck1)
	.byte $0c+__dpcm_offset,$96,$09	;54 (yourloss)
	.byte $32+__dpcm_offset,$a4,$09	;55 (worth)
	.byte $5b+__dpcm_offset,$64,$09	;56 (rikuto)
	.byte $74+__dpcm_offset,$9f,$09	;57 (punish)
	.byte $9c+__dpcm_offset,$ae,$09	;58 (Ohmy_whatdowehav)
	.byte $c8+__dpcm_offset,$5a,$09	;59 (innocent)
	.byte $df+__dpcm_offset,$7a,$09	;60 (fun)
	
.Lenv0:
	.byte $c0,$00,$00
.Lenv1:
	.byte $c5,$ca,$c8,$c6,$c4,$00,$04
.Lenv2:
	.byte $c3,$c6,$c5,$c3,$c2,$00,$04

