;this file for FamiTone2 library generated by text2data tool

DMCmusic_ingame_data:
	.byte 1
	.word 1
	.word .Lsamples-3

.Lsamples:
	.byte $00+__dpcm_offset,$6d,$0f	;1 (fuck3)
	.byte $1c+__dpcm_offset,$a4,$0f	;2 (fuck2)
	.byte $45+__dpcm_offset,$66,$0f	;3 (fuck1)
