# ----------------------------
# Makefile Options
# ----------------------------

NAME = CIRIGHT
ICON = icon.png
DESCRIPTION = "Gay game"
COMPRESSED = NO
ARCHIVED = YES

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
