CC = wcl
MODE = h

# -DTHIRTYTWOBITS
CFLAGS = -0 -bt=dos  -m${MODE} -I./src/dosmid -I./src/generic -I./src/graphics -I./src -I./src/graphics/vga -I./src/input
CFLAGS += -DOPL -DSBAWE -zi

LDFLAGS = -bcl=dos 
OUTPUT = EGA.exe

SOURCES =  EGATEST.C

OBJS = EGATEST.C

all: asm ${OUTPUT}

asm:
	wasm src/graphics/8514/CALLAFI.ASM 

${OUTPUT}: ${SOURCES}
	${CC} ${CFLAGS} ${LDFLAGS} -fe=${OUTPUT} ${OBJS} CALLAFI.o 
	
clean:
	rm *.o src/*.o
	rm ${OUTPUT}
