CC = wcl
MODE = c

# -DTHIRTYTWOBITS
CFLAGS = -bt=dos -m${MODE} -zt=84 -I./src/dosmid -I./src/generic -I./src/graphics -I./src -I./src/graphics/vga -I./src/input
CFLAGS += -DOPL -DSBAWE

LDFLAGS = -bcl=dos -k32000 -ze -s
OUTPUT = main.exe

SOURCES = VESA.c
OBJS = VESA.c

${OUTPUT}: ${SOURCES}
	${CC} ${CFLAGS} ${LDFLAGS} -fe=${OUTPUT} ${OBJS} ./src/dosmid/awe32/rawe32$(MODE).lib
	
clean:
	rm *.o
	rm ${OUTPUT}
